disciple_influence = {'follower': 1,'acolyte': 2,'sage': 3 }
player_colors = ["red", "blue"]
client_actions = ["pass", "select_a_tile"]
disciples = ['follower', 'acolyte', 'sage']
all_tile_indices = list(range(9))
number_of_initial_followers_to_place = 4
starting_cost_to_recruit = {'follower': 2, 'acolyte': 3, 'sage': 4}
starting_cost_to_exile = {'follower': 3, 'acolyte': 4, 'sage': 5}
initial_recruiting_ranges = {'red': 0, 'blue': 0}
initial_exiling_ranges = {'red': 0, 'blue': 0}
starting_leader_movement = {'red': 1, 'blue': 1}
grid_size = 3
leader_influence = 3
power_given_at_start_of_round = [3,4,5,6,7,8]
corner_tiles = [0,2,6,8]
number_of_scoring_bonuses = 6
number_of_income_bonuses = 6