"""create_user_table_and_add_user_foreign_keys

Revision ID: 76b226733675
Revises: c5952166191c
Create Date: 2024-10-24 08:20:11.186994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76b226733675'
down_revision: Union[str, None] = 'c5952166191c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('games', sa.Column('player1_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('player2_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('games', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'games', 'users', ['player1_id'], ['id'])
    op.create_foreign_key(None, 'games', 'users', ['player2_id'], ['id'])
    op.add_column('lobby_tables', sa.Column('player1_id', sa.Integer(), nullable=True))
    op.add_column('lobby_tables', sa.Column('player2_id', sa.Integer(), nullable=True))
    op.add_column('lobby_tables', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('lobby_tables', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'lobby_tables', 'users', ['player1_id'], ['id'])
    op.create_foreign_key(None, 'lobby_tables', 'users', ['player2_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lobby_tables', type_='foreignkey')
    op.drop_constraint(None, 'lobby_tables', type_='foreignkey')
    op.drop_column('lobby_tables', 'updated_at')
    op.drop_column('lobby_tables', 'created_at')
    op.drop_column('lobby_tables', 'player2_id')
    op.drop_column('lobby_tables', 'player1_id')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'updated_at')
    op.drop_column('games', 'created_at')
    op.drop_column('games', 'player2_id')
    op.drop_column('games', 'player1_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
