"""Initial migration

Revision ID: c5952166191c
Revises: 
Create Date: 2024-10-05 12:11:44.469432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5952166191c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('player1_token', sa.String(), nullable=True),
    sa.Column('player2_token', sa.String(), nullable=True),
    sa.Column('game_state', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_table('lobby_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('Waiting', 'Full', name='lobby_status'), nullable=True),
    sa.Column('player1_token', sa.String(), nullable=True),
    sa.Column('player2_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lobby_tables_id'), 'lobby_tables', ['id'], unique=False)
    op.create_index(op.f('ix_lobby_tables_name'), 'lobby_tables', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lobby_tables_name'), table_name='lobby_tables')
    op.drop_index(op.f('ix_lobby_tables_id'), table_name='lobby_tables')
    op.drop_table('lobby_tables')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
