"""Update Player model with foreign keys to LobbyTable and Game

Revision ID: cf09db0a3441
Revises: ad9f71786956
Create Date: 2024-06-18 09:28:14.951962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf09db0a3441'
down_revision: Union[str, None] = 'ad9f71786956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lobby_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lobby_tables_id'), 'lobby_tables', ['id'], unique=False)
    op.create_index(op.f('ix_lobby_tables_name'), 'lobby_tables', ['name'], unique=False)
    op.create_index(op.f('ix_lobby_tables_status'), 'lobby_tables', ['status'], unique=False)
    op.drop_index('ix_lobby_games_id', table_name='lobby_games')
    op.drop_index('ix_lobby_games_name', table_name='lobby_games')
    op.drop_index('ix_lobby_games_status', table_name='lobby_games')
    op.drop_table('lobby_games')
    op.add_column('players', sa.Column('lobby_table_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'players', 'lobby_tables', ['lobby_table_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_column('players', 'lobby_table_id')
    op.create_table('lobby_games',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='lobby_games_pkey')
    )
    op.create_index('ix_lobby_games_status', 'lobby_games', ['status'], unique=False)
    op.create_index('ix_lobby_games_name', 'lobby_games', ['name'], unique=False)
    op.create_index('ix_lobby_games_id', 'lobby_games', ['id'], unique=False)
    op.drop_index(op.f('ix_lobby_tables_status'), table_name='lobby_tables')
    op.drop_index(op.f('ix_lobby_tables_name'), table_name='lobby_tables')
    op.drop_index(op.f('ix_lobby_tables_id'), table_name='lobby_tables')
    op.drop_table('lobby_tables')
    # ### end Alembic commands ###
